# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'JFABaseKit' do
    pod 'FXPageControl', '~> 1.4'
    pod 'SSLunarDate', '~> 0.0.1'
    pod 'CHTCollectionViewWaterfallLayout', '~> 0.8'
    pod 'ViewDeck', '~> 2.3.1'
    pod 'KVOController', '~> 1.0.3'
    pod 'Block-KVO', '~> 2.2.1'
    pod 'MBProgressHUD', '~> 0.9'
    pod 'AFNetworking', '~> 2.5.0'
    pod 'AFNetworking+SingleBlock', '~> 0.0.1'
    pod 'BlocksKit', '~> 2.2.5'

end

target 'JFABaseKitTests' do

end

